// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: kvapi.proto

package kvapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Kvgo_Write_FullMethodName  = "/lynkdb.kvapi.v2.Kvgo/Write"
	Kvgo_Delete_FullMethodName = "/lynkdb.kvapi.v2.Kvgo/Delete"
	Kvgo_Read_FullMethodName   = "/lynkdb.kvapi.v2.Kvgo/Read"
	Kvgo_Range_FullMethodName  = "/lynkdb.kvapi.v2.Kvgo/Range"
	Kvgo_Batch_FullMethodName  = "/lynkdb.kvapi.v2.Kvgo/Batch"
)

// KvgoClient is the client API for Kvgo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvgoClient interface {
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*ResultSet, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*ResultSet, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ResultSet, error)
	Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*ResultSet, error)
	Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type kvgoClient struct {
	cc grpc.ClientConnInterface
}

func NewKvgoClient(cc grpc.ClientConnInterface) KvgoClient {
	return &kvgoClient{cc}
}

func (c *kvgoClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*ResultSet, error) {
	out := new(ResultSet)
	err := c.cc.Invoke(ctx, Kvgo_Write_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvgoClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*ResultSet, error) {
	out := new(ResultSet)
	err := c.cc.Invoke(ctx, Kvgo_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvgoClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ResultSet, error) {
	out := new(ResultSet)
	err := c.cc.Invoke(ctx, Kvgo_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvgoClient) Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*ResultSet, error) {
	out := new(ResultSet)
	err := c.cc.Invoke(ctx, Kvgo_Range_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvgoClient) Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, Kvgo_Batch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvgoServer is the server API for Kvgo service.
// All implementations must embed UnimplementedKvgoServer
// for forward compatibility
type KvgoServer interface {
	Write(context.Context, *WriteRequest) (*ResultSet, error)
	Delete(context.Context, *DeleteRequest) (*ResultSet, error)
	Read(context.Context, *ReadRequest) (*ResultSet, error)
	Range(context.Context, *RangeRequest) (*ResultSet, error)
	Batch(context.Context, *BatchRequest) (*BatchResponse, error)
	mustEmbedUnimplementedKvgoServer()
}

// UnimplementedKvgoServer must be embedded to have forward compatible implementations.
type UnimplementedKvgoServer struct {
}

func (UnimplementedKvgoServer) Write(context.Context, *WriteRequest) (*ResultSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedKvgoServer) Delete(context.Context, *DeleteRequest) (*ResultSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKvgoServer) Read(context.Context, *ReadRequest) (*ResultSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedKvgoServer) Range(context.Context, *RangeRequest) (*ResultSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Range not implemented")
}
func (UnimplementedKvgoServer) Batch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Batch not implemented")
}
func (UnimplementedKvgoServer) mustEmbedUnimplementedKvgoServer() {}

// UnsafeKvgoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvgoServer will
// result in compilation errors.
type UnsafeKvgoServer interface {
	mustEmbedUnimplementedKvgoServer()
}

func RegisterKvgoServer(s grpc.ServiceRegistrar, srv KvgoServer) {
	s.RegisterService(&Kvgo_ServiceDesc, srv)
}

func _Kvgo_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvgoServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvgo_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvgoServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvgo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvgoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvgo_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvgoServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvgo_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvgoServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvgo_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvgoServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvgo_Range_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvgoServer).Range(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvgo_Range_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvgoServer).Range(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvgo_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvgoServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvgo_Batch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvgoServer).Batch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kvgo_ServiceDesc is the grpc.ServiceDesc for Kvgo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kvgo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynkdb.kvapi.v2.Kvgo",
	HandlerType: (*KvgoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Kvgo_Write_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Kvgo_Delete_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Kvgo_Read_Handler,
		},
		{
			MethodName: "Range",
			Handler:    _Kvgo_Range_Handler,
		},
		{
			MethodName: "Batch",
			Handler:    _Kvgo_Batch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvapi.proto",
}
