// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: kvapi_internal.proto

package kvapi

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// KvgoInternalClient is the client API for KvgoInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvgoInternalClient interface {
}

type kvgoInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewKvgoInternalClient(cc grpc.ClientConnInterface) KvgoInternalClient {
	return &kvgoInternalClient{cc}
}

// KvgoInternalServer is the server API for KvgoInternal service.
// All implementations must embed UnimplementedKvgoInternalServer
// for forward compatibility
type KvgoInternalServer interface {
	mustEmbedUnimplementedKvgoInternalServer()
}

// UnimplementedKvgoInternalServer must be embedded to have forward compatible implementations.
type UnimplementedKvgoInternalServer struct {
}

func (UnimplementedKvgoInternalServer) mustEmbedUnimplementedKvgoInternalServer() {}

// UnsafeKvgoInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvgoInternalServer will
// result in compilation errors.
type UnsafeKvgoInternalServer interface {
	mustEmbedUnimplementedKvgoInternalServer()
}

func RegisterKvgoInternalServer(s grpc.ServiceRegistrar, srv KvgoInternalServer) {
	s.RegisterService(&KvgoInternal_ServiceDesc, srv)
}

// KvgoInternal_ServiceDesc is the grpc.ServiceDesc for KvgoInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KvgoInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynkdb.kvapi.v2.KvgoInternal",
	HandlerType: (*KvgoInternalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "kvapi_internal.proto",
}
