// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.14.0
// source: kvapi_internal.proto

package kvapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
	Attrs   uint64 `protobuf:"varint,3,opt,name=attrs,proto3" json:"attrs,omitempty" toml:"attrs,omitempty"`
	Expired int64  `protobuf:"varint,4,opt,name=expired,proto3" json:"expired,omitempty" toml:"expired,omitempty"`
	Created int64  `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty" toml:"created,omitempty"`
	Size    int32  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty" toml:"size,omitempty"`
	Key     []byte `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty" toml:"key,omitempty"`
}

func (x *LogMeta) Reset() {
	*x = LogMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMeta) ProtoMessage() {}

func (x *LogMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMeta.ProtoReflect.Descriptor instead.
func (*LogMeta) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{0}
}

func (x *LogMeta) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogMeta) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LogMeta) GetAttrs() uint64 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

func (x *LogMeta) GetExpired() int64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

func (x *LogMeta) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *LogMeta) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LogMeta) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RawKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty" toml:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty"`
}

func (x *RawKeyValue) Reset() {
	*x = RawKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawKeyValue) ProtoMessage() {}

func (x *RawKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawKeyValue.ProtoReflect.Descriptor instead.
func (*RawKeyValue) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{1}
}

func (x *RawKeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawKeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type TableMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Version uint64            `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
	Shards  []*TableMap_Shard `protobuf:"bytes,9,rep,name=shards,proto3" json:"shards,omitempty" toml:"shards,omitempty"`
}

func (x *TableMap) Reset() {
	*x = TableMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMap) ProtoMessage() {}

func (x *TableMap) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMap.ProtoReflect.Descriptor instead.
func (*TableMap) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{2}
}

func (x *TableMap) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TableMap) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TableMap) GetShards() []*TableMap_Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type SysNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
}

func (x *SysNode) Reset() {
	*x = SysNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysNode) ProtoMessage() {}

func (x *SysNode) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysNode.ProtoReflect.Descriptor instead.
func (*SysNode) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{3}
}

func (x *SysNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SysVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty" toml:"node_id,omitempty"` // string mountpoint = 3;
}

func (x *SysVolume) Reset() {
	*x = SysVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysVolume) ProtoMessage() {}

func (x *SysVolume) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysVolume.ProtoReflect.Descriptor instead.
func (*SysVolume) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{4}
}

func (x *SysVolume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SysVolume) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SysVolumeStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	CapacityUsed   uint64 `protobuf:"varint,8,opt,name=capacity_used,json=capacityUsed,proto3" json:"capacity_used,omitempty" toml:"capacity_used,omitempty"`
	CapacityFree   uint64 `protobuf:"varint,9,opt,name=capacity_free,json=capacityFree,proto3" json:"capacity_free,omitempty" toml:"capacity_free,omitempty"`
	LoadCycleCount uint64 `protobuf:"varint,10,opt,name=load_cycle_count,json=loadCycleCount,proto3" json:"load_cycle_count,omitempty" toml:"load_cycle_count,omitempty"`
	Updated        uint64 `protobuf:"varint,15,opt,name=updated,proto3" json:"updated,omitempty" toml:"updated,omitempty"`
}

func (x *SysVolumeStatus) Reset() {
	*x = SysVolumeStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysVolumeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysVolumeStatus) ProtoMessage() {}

func (x *SysVolumeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysVolumeStatus.ProtoReflect.Descriptor instead.
func (*SysVolumeStatus) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{5}
}

func (x *SysVolumeStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SysVolumeStatus) GetCapacityUsed() uint64 {
	if x != nil {
		return x.CapacityUsed
	}
	return 0
}

func (x *SysVolumeStatus) GetCapacityFree() uint64 {
	if x != nil {
		return x.CapacityFree
	}
	return 0
}

func (x *SysVolumeStatus) GetLoadCycleCount() uint64 {
	if x != nil {
		return x.LoadCycleCount
	}
	return 0
}

func (x *SysVolumeStatus) GetUpdated() uint64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type WriteProposalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Write *WriteRequest `protobuf:"bytes,2,opt,name=write,proto3" json:"write,omitempty" toml:"write,omitempty"` // uint64 expired = 3;
}

func (x *WriteProposalRequest) Reset() {
	*x = WriteProposalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteProposalRequest) ProtoMessage() {}

func (x *WriteProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteProposalRequest.ProtoReflect.Descriptor instead.
func (*WriteProposalRequest) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{6}
}

func (x *WriteProposalRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WriteProposalRequest) GetWrite() *WriteRequest {
	if x != nil {
		return x.Write
	}
	return nil
}

type DeleteProposalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Key   []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" toml:"key,omitempty"`
	Meta  *Meta  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty" toml:"meta,omitempty"`
	Attrs uint64 `protobuf:"varint,4,opt,name=attrs,proto3" json:"attrs,omitempty" toml:"attrs,omitempty"` // uint64 expired = 4;
}

func (x *DeleteProposalRequest) Reset() {
	*x = DeleteProposalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProposalRequest) ProtoMessage() {}

func (x *DeleteProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProposalRequest.ProtoReflect.Descriptor instead.
func (*DeleteProposalRequest) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProposalRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteProposalRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteProposalRequest) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DeleteProposalRequest) GetAttrs() uint64 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

type LogRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId   string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty" toml:"table_id,omitempty"`
	ShardId   uint64 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty" toml:"shard_id,omitempty"`
	ReplicaId uint64 `protobuf:"varint,3,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty" toml:"replica_id,omitempty"`
	LowerLog  uint64 `protobuf:"varint,4,opt,name=lower_log,json=lowerLog,proto3" json:"lower_log,omitempty" toml:"lower_log,omitempty"`
	UpperLog  uint64 `protobuf:"varint,5,opt,name=upper_log,json=upperLog,proto3" json:"upper_log,omitempty" toml:"upper_log,omitempty"`
}

func (x *LogRangeRequest) Reset() {
	*x = LogRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRangeRequest) ProtoMessage() {}

func (x *LogRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRangeRequest.ProtoReflect.Descriptor instead.
func (*LogRangeRequest) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{8}
}

func (x *LogRangeRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *LogRangeRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *LogRangeRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *LogRangeRequest) GetLowerLog() uint64 {
	if x != nil {
		return x.LowerLog
	}
	return 0
}

func (x *LogRangeRequest) GetUpperLog() uint64 {
	if x != nil {
		return x.UpperLog
	}
	return 0
}

type LogRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uint64 log_left = 7;
	LogOffset         uint64     `protobuf:"varint,8,opt,name=log_offset,json=logOffset,proto3" json:"log_offset,omitempty" toml:"log_offset,omitempty"`
	Items             []*LogMeta `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty" toml:"items,omitempty"`
	NextResultSet     bool       `protobuf:"varint,10,opt,name=next_result_set,json=nextResultSet,proto3" json:"next_result_set,omitempty" toml:"next_result_set,omitempty"`
	LogOffsetOutrange bool       `protobuf:"varint,11,opt,name=log_offset_outrange,json=logOffsetOutrange,proto3" json:"log_offset_outrange,omitempty" toml:"log_offset_outrange,omitempty"`
}

func (x *LogRangeResponse) Reset() {
	*x = LogRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRangeResponse) ProtoMessage() {}

func (x *LogRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRangeResponse.ProtoReflect.Descriptor instead.
func (*LogRangeResponse) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{9}
}

func (x *LogRangeResponse) GetLogOffset() uint64 {
	if x != nil {
		return x.LogOffset
	}
	return 0
}

func (x *LogRangeResponse) GetItems() []*LogMeta {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LogRangeResponse) GetNextResultSet() bool {
	if x != nil {
		return x.NextResultSet
	}
	return false
}

func (x *LogRangeResponse) GetLogOffsetOutrange() bool {
	if x != nil {
		return x.LogOffsetOutrange
	}
	return false
}

type LogKeyRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId   string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty" toml:"table_id,omitempty"`
	ShardId   uint64 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty" toml:"shard_id,omitempty"`
	ReplicaId uint64 `protobuf:"varint,3,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty" toml:"replica_id,omitempty"`
	LowerKey  []byte `protobuf:"bytes,4,opt,name=lower_key,json=lowerKey,proto3" json:"lower_key,omitempty" toml:"lower_key,omitempty"`
	UpperKey  []byte `protobuf:"bytes,5,opt,name=upper_key,json=upperKey,proto3" json:"upper_key,omitempty" toml:"upper_key,omitempty"`
}

func (x *LogKeyRangeRequest) Reset() {
	*x = LogKeyRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogKeyRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogKeyRangeRequest) ProtoMessage() {}

func (x *LogKeyRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogKeyRangeRequest.ProtoReflect.Descriptor instead.
func (*LogKeyRangeRequest) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{10}
}

func (x *LogKeyRangeRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *LogKeyRangeRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *LogKeyRangeRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *LogKeyRangeRequest) GetLowerKey() []byte {
	if x != nil {
		return x.LowerKey
	}
	return nil
}

func (x *LogKeyRangeRequest) GetUpperKey() []byte {
	if x != nil {
		return x.UpperKey
	}
	return nil
}

type LogKeyRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items         []*Meta `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty" toml:"items,omitempty"`
	NextResultSet bool    `protobuf:"varint,10,opt,name=next_result_set,json=nextResultSet,proto3" json:"next_result_set,omitempty" toml:"next_result_set,omitempty"`
}

func (x *LogKeyRangeResponse) Reset() {
	*x = LogKeyRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogKeyRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogKeyRangeResponse) ProtoMessage() {}

func (x *LogKeyRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogKeyRangeResponse.ProtoReflect.Descriptor instead.
func (*LogKeyRangeResponse) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{11}
}

func (x *LogKeyRangeResponse) GetItems() []*Meta {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LogKeyRangeResponse) GetNextResultSet() bool {
	if x != nil {
		return x.NextResultSet
	}
	return false
}

type TableMap_Replica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
	StoreId string `protobuf:"bytes,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty" toml:"store_id,omitempty"`
	Action  uint64 `protobuf:"varint,7,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
}

func (x *TableMap_Replica) Reset() {
	*x = TableMap_Replica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableMap_Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMap_Replica) ProtoMessage() {}

func (x *TableMap_Replica) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMap_Replica.ProtoReflect.Descriptor instead.
func (*TableMap_Replica) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TableMap_Replica) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TableMap_Replica) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TableMap_Replica) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *TableMap_Replica) GetAction() uint64 {
	if x != nil {
		return x.Action
	}
	return 0
}

type TableMap_Shard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Version  uint64              `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
	LowerKey []byte              `protobuf:"bytes,5,opt,name=lower_key,json=lowerKey,proto3" json:"lower_key,omitempty" toml:"lower_key,omitempty"`
	UpperKey []byte              `protobuf:"bytes,6,opt,name=upper_key,json=upperKey,proto3" json:"upper_key,omitempty" toml:"upper_key,omitempty"`
	Action   uint64              `protobuf:"varint,7,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
	Replicas []*TableMap_Replica `protobuf:"bytes,9,rep,name=replicas,proto3" json:"replicas,omitempty" toml:"replicas,omitempty"`
}

func (x *TableMap_Shard) Reset() {
	*x = TableMap_Shard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvapi_internal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableMap_Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMap_Shard) ProtoMessage() {}

func (x *TableMap_Shard) ProtoReflect() protoreflect.Message {
	mi := &file_kvapi_internal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMap_Shard.ProtoReflect.Descriptor instead.
func (*TableMap_Shard) Descriptor() ([]byte, []int) {
	return file_kvapi_internal_proto_rawDescGZIP(), []int{2, 1}
}

func (x *TableMap_Shard) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TableMap_Shard) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TableMap_Shard) GetLowerKey() []byte {
	if x != nil {
		return x.LowerKey
	}
	return nil
}

func (x *TableMap_Shard) GetUpperKey() []byte {
	if x != nil {
		return x.UpperKey
	}
	return nil
}

func (x *TableMap_Shard) GetAction() uint64 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *TableMap_Shard) GetReplicas() []*TableMap_Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

var File_kvapi_internal_proto protoreflect.FileDescriptor

var file_kvapi_internal_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6b, 0x76, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6b,
	0x76, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x1a, 0x0b, 0x6b, 0x76, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74,
	0x74, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x0b, 0x52, 0x61,
	0x77, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x9a, 0x03, 0x0a, 0x08, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64,
	0x62, 0x2e, 0x6b, 0x76, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x4d, 0x61, 0x70, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x73, 0x1a, 0x66, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xc2, 0x01, 0x0a, 0x05, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70,
	0x70, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75,
	0x70, 0x70, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3d, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x32, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x19,
	0x0a, 0x07, 0x53, 0x79, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x09, 0x53, 0x79, 0x73,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22,
	0xaf, 0x01, 0x0a, 0x0f, 0x53, 0x79, 0x73, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f,
	0x75, 0x73, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x55, 0x73, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x46, 0x72, 0x65, 0x65, 0x12, 0x28, 0x0a,
	0x10, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x79, 0x63,
	0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x5b, 0x0a, 0x14, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64,
	0x62, 0x2e, 0x6b, 0x76, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x22, 0x7a,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62,
	0x2e, 0x6b, 0x76, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x0f, 0x4c,
	0x6f, 0x67, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x70, 0x70, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x22, 0xb9, 0x01,
	0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x32, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x5f, 0x73, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x6c, 0x6f, 0x67,
	0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x6c, 0x6f, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x4f, 0x75, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x12, 0x4c, 0x6f,
	0x67, 0x4b, 0x65, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x70, 0x70, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x22,
	0x6a, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6b,
	0x76, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6e, 0x65,
	0x78, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x32, 0x0e, 0x0a, 0x0c, 0x4b,
	0x76, 0x67, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x0c, 0x48, 0x03, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x6b, 0x76, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kvapi_internal_proto_rawDescOnce sync.Once
	file_kvapi_internal_proto_rawDescData = file_kvapi_internal_proto_rawDesc
)

func file_kvapi_internal_proto_rawDescGZIP() []byte {
	file_kvapi_internal_proto_rawDescOnce.Do(func() {
		file_kvapi_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_kvapi_internal_proto_rawDescData)
	})
	return file_kvapi_internal_proto_rawDescData
}

var file_kvapi_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_kvapi_internal_proto_goTypes = []interface{}{
	(*LogMeta)(nil),               // 0: lynkdb.kvapi.v2.LogMeta
	(*RawKeyValue)(nil),           // 1: lynkdb.kvapi.v2.RawKeyValue
	(*TableMap)(nil),              // 2: lynkdb.kvapi.v2.TableMap
	(*SysNode)(nil),               // 3: lynkdb.kvapi.v2.SysNode
	(*SysVolume)(nil),             // 4: lynkdb.kvapi.v2.SysVolume
	(*SysVolumeStatus)(nil),       // 5: lynkdb.kvapi.v2.SysVolumeStatus
	(*WriteProposalRequest)(nil),  // 6: lynkdb.kvapi.v2.WriteProposalRequest
	(*DeleteProposalRequest)(nil), // 7: lynkdb.kvapi.v2.DeleteProposalRequest
	(*LogRangeRequest)(nil),       // 8: lynkdb.kvapi.v2.LogRangeRequest
	(*LogRangeResponse)(nil),      // 9: lynkdb.kvapi.v2.LogRangeResponse
	(*LogKeyRangeRequest)(nil),    // 10: lynkdb.kvapi.v2.LogKeyRangeRequest
	(*LogKeyRangeResponse)(nil),   // 11: lynkdb.kvapi.v2.LogKeyRangeResponse
	(*TableMap_Replica)(nil),      // 12: lynkdb.kvapi.v2.TableMap.Replica
	(*TableMap_Shard)(nil),        // 13: lynkdb.kvapi.v2.TableMap.Shard
	(*WriteRequest)(nil),          // 14: lynkdb.kvapi.v2.WriteRequest
	(*Meta)(nil),                  // 15: lynkdb.kvapi.v2.Meta
}
var file_kvapi_internal_proto_depIdxs = []int32{
	13, // 0: lynkdb.kvapi.v2.TableMap.shards:type_name -> lynkdb.kvapi.v2.TableMap.Shard
	14, // 1: lynkdb.kvapi.v2.WriteProposalRequest.write:type_name -> lynkdb.kvapi.v2.WriteRequest
	15, // 2: lynkdb.kvapi.v2.DeleteProposalRequest.meta:type_name -> lynkdb.kvapi.v2.Meta
	0,  // 3: lynkdb.kvapi.v2.LogRangeResponse.items:type_name -> lynkdb.kvapi.v2.LogMeta
	15, // 4: lynkdb.kvapi.v2.LogKeyRangeResponse.items:type_name -> lynkdb.kvapi.v2.Meta
	12, // 5: lynkdb.kvapi.v2.TableMap.Shard.replicas:type_name -> lynkdb.kvapi.v2.TableMap.Replica
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kvapi_internal_proto_init() }
func file_kvapi_internal_proto_init() {
	if File_kvapi_internal_proto != nil {
		return
	}
	file_kvapi_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kvapi_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysVolumeStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteProposalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProposalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogKeyRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogKeyRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableMap_Replica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvapi_internal_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableMap_Shard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kvapi_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvapi_internal_proto_goTypes,
		DependencyIndexes: file_kvapi_internal_proto_depIdxs,
		MessageInfos:      file_kvapi_internal_proto_msgTypes,
	}.Build()
	File_kvapi_internal_proto = out.File
	file_kvapi_internal_proto_rawDesc = nil
	file_kvapi_internal_proto_goTypes = nil
	file_kvapi_internal_proto_depIdxs = nil
}
